/**
 * Client store action types.
 * @enum {string}
 */
export const ACTIONS = {
  LINES: "LINES",
  AUTHENTICATION: "AUTHENTICATION",
  LOADING_APP: "LOADING-APP",
  LOADING: "LOADING",
  PUSH_SUBSCRIPTION: "PUSH-SUBSCRIPTION",
  LINE_SUBSCRIPTION: "LINE-SUBSCRIPTION",
};
